source 'https://rubygems.org'

gem 'sprockets-helpers'
gem 'sprockets-sass'
gem 'oily_png'
gem 'jekyll'
gem 'jekyll-assets'
gem 'uglifier'
gem 'sass'
gem 'compass', '>1'
gem 'coffee-script'
gem 'haml'
